test:
	nvim --headless --clean -u tests/test.lua "$(FILE)"
docs:
	md2vim -desc "*orgmode* *orgmode.nvim*\n* NOTE: This file is autogenerated from DOCS.md file" DOCS.md doc/orgmode.txt
api_docs:
	nvim --headless --clean -u ./scripts/gendoc.lua
format:
	stylua lua/ tests/
