 (expr "*" @bold)
 (expr "/" @italic)
 (expr "~" @code)
 (expr "_" @underline)
 (expr "=" @verbatim)
 (expr "+" @strikethrough)
 (expr "[" @footnote.start "str" @_fn ":" (#eq? @_fn "fn"))
 (expr "]" @footnote.end)
 (expr "\\" "str" @latex.plain)
 (expr "\\" "(" @latex.bracket.start)
 (expr "\\" ")" @latex.bracket.end)
 (expr "\\" "{" @latex.curly.start)
 (expr "\\" "}" @latex.curly.end)
 (expr "\\" "[" @latex.square.start)
 (expr "\\" "]" @latex.square.end)
