(paragraph ((expr "*" @bold.start _) (expr _ "*" @bold.end) (#org-is-valid-markup-range? @bold.start @bold.end)))
(paragraph (expr "*" @bold.start _ "*" @bold.end (#org-is-valid-markup-range? @bold.start @bold.end)))
(paragraph ((expr "~" @code.start _) (expr _ "~" @code.end) (#org-is-valid-markup-range? @code.start @code.end)))
(paragraph (expr "~" @code.start _ "~" @code.end (#org-is-valid-markup-range? @code.start @code.end)))
(paragraph ((expr "/" @italic.start _) (expr _ "/" @italic.end) (#org-is-valid-markup-range? @italic.start @italic.end)))
(paragraph (expr "/" @italic.start _ "/" @italic.end (#org-is-valid-markup-range? @italic.start @italic.end)))
(paragraph ((expr "_" @underline.start _) (expr _ "_" @underline.end) (#org-is-valid-markup-range? @underline.start @underline.end)))
(paragraph (expr "_" @underline.start _ "_" @underline.end (#org-is-valid-markup-range? @underline.start @underline.end)))
(paragraph ((expr "=" @verbatim.start _) (expr _ "=" @verbatim.end) (#org-is-valid-markup-range? @verbatim.start @verbatim.end)))
(paragraph (expr "=" @verbatim.start _ "=" @verbatim.end (#org-is-valid-markup-range? @verbatim.start @verbatim.end)))
(paragraph ((expr "+" @strikethrough.start _) (expr _ "+" @strikethrough.end) (#org-is-valid-markup-range? @strikethrough.start @strikethrough.end)))
(paragraph (expr "+" @strikethrough.start _ "+" @strikethrough.end (#org-is-valid-markup-range? @strikethrough.start @strikethrough.end)))
(paragraph ((expr "[" @hyperlink.start . "[" _) (expr _ "]" . "]" @hyperlink.end) (#org-is-valid-hyperlink-range? @hyperlink.start @hyperlink.end)))
(paragraph (expr "[" @hyperlink.start . "[" _  "]" . "]" @hyperlink.end (#org-is-valid-hyperlink-range? @hyperlink.start @hyperlink.end)))
(paragraph ((expr ("\\" @text.math.start.left "(" @text.math.start.right)) (expr ("\\" ")" @text.math.end)) (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end)))
(paragraph (expr "\\" @text.math.start.left "(" @text.math.start.right "\\" ")" @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end)))
(paragraph ((expr ("\\" @text.math.start.left ("str")+ @text.math.start.right "{")) (expr "}" @text.math.end) (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end)))
(paragraph (expr "\\" @text.math.start.left ("str")+ @text.math.start.right "{" "}" @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end)))
(paragraph (expr "\\" @text.math.start.left ("str")+ @text.math.start.right @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end)))

(item ((expr "*" @bold.start _) (expr _ "*" @bold.end) (#org-is-valid-markup-range? @bold.start @bold.end)))
(item (expr "*" @bold.start _ "*" @bold.end (#org-is-valid-markup-range? @bold.start @bold.end)))
(item ((expr "~" @code.start _) (expr _ "~" @code.end) (#org-is-valid-markup-range? @code.start @code.end)))
(item (expr "~" @code.start _ "~" @code.end (#org-is-valid-markup-range? @code.start @code.end)))
(item ((expr "/" @italic.start _) (expr _ "/" @italic.end) (#org-is-valid-markup-range? @italic.start @italic.end)))
(item (expr "/" @italic.start _ "/" @italic.end (#org-is-valid-markup-range? @italic.start @italic.end)))
(item ((expr "_" @underline.start _) (expr _ "_" @underline.end) (#org-is-valid-markup-range? @underline.start @underline.end)))
(item (expr "_" @underline.start _ "_" @underline.end (#org-is-valid-markup-range? @underline.start @underline.end)))
(item ((expr "=" @verbatim.start _) (expr _ "=" @verbatim.end) (#org-is-valid-markup-range? @verbatim.start @verbatim.end)))
(item (expr "=" @verbatim.start _ "=" @verbatim.end (#org-is-valid-markup-range? @verbatim.start @verbatim.end)))
(item ((expr "+" @strikethrough.start _) (expr _ "+" @strikethrough.end) (#org-is-valid-markup-range? @strikethrough.start @strikethrough.end)))
(item (expr "+" @strikethrough.start _ "+" @strikethrough.end (#org-is-valid-markup-range? @strikethrough.start @strikethrough.end)))
(item ((expr "[" @hyperlink.start . "[" _) (expr _ "]" . "]" @hyperlink.end) (#org-is-valid-hyperlink-range? @hyperlink.start @hyperlink.end)))
(item (expr "[" @hyperlink.start . "[" _  "]" . "]" @hyperlink.end (#org-is-valid-hyperlink-range? @hyperlink.start @hyperlink.end)))
(item ((expr ("\\" @text.math.start.left "(" @text.math.start.right)) (expr ("\\" ")" @text.math.end)) (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end)))
(item (expr "\\" @text.math.start.left "(" @text.math.start.right "\\" ")" @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end)))
(item ((expr ("\\" @text.math.start.left ("str")+ @text.math.start.right "{")) (expr "}" @text.math.end) (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end)))
(item (expr "\\" @text.math.start.left ("str")+ @text.math.start.right "{" "}" @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end)))
(item (expr "\\" @text.math.start.left ("str")+ @text.math.start.right @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end)))

(cell (contents ((expr "*" @bold.start _) (expr _ "*" @bold.end) (#org-is-valid-markup-range? @bold.start @bold.end))))
(cell (contents (expr "*" @bold.start _ "*" @bold.end (#org-is-valid-markup-range? @bold.start @bold.end))))
(cell (contents ((expr "~" @code.start _) (expr _ "~" @code.end) (#org-is-valid-markup-range? @code.start @code.end))))
(cell (contents (expr "~" @code.start _ "~" @code.end (#org-is-valid-markup-range? @code.start @code.end))))
(cell (contents (expr "/" @italic.start _ "/" @italic.end (#org-is-valid-markup-range? @italic.start @italic.end))))
(cell (contents ((expr "_" @underline.start _) (expr _ "_" @underline.end) (#org-is-valid-markup-range? @underline.start @underline.end))))
(cell (contents (expr "_" @underline.start _ "_" @underline.end (#org-is-valid-markup-range? @underline.start @underline.end))))
(cell (contents ((expr "=" @verbatim.start _) (expr _ "=" @verbatim.end) (#org-is-valid-markup-range? @verbatim.start @verbatim.end))))
(cell (contents (expr "=" @verbatim.start _ "=" @verbatim.end (#org-is-valid-markup-range? @verbatim.start @verbatim.end))))
(cell (contents ((expr "+" @strikethrough.start _) (expr _ "+" @strikethrough.end) (#org-is-valid-markup-range? @strikethrough.start @strikethrough.end))))
(cell (contents (expr "+" @strikethrough.start _ "+" @strikethrough.end (#org-is-valid-markup-range? @strikethrough.start @strikethrough.end))))
(cell (contents ((expr "[" @hyperlink.start . "[" _) (expr _ "]" . "]" @hyperlink.end) (#org-is-valid-hyperlink-range? @hyperlink.start @hyperlink.end))))
(cell (contents (expr "[" @hyperlink.start . "[" _  "]" . "]" @hyperlink.end (#org-is-valid-hyperlink-range? @hyperlink.start @hyperlink.end))))
(cell (contents ((expr ("\\" @text.math.start.left "(" @text.math.start.right)) (expr ("\\" ")" @text.math.end)) (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))))
(cell (contents (expr "\\" @text.math.start.left "(" @text.math.start.right "\\" ")" @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))))
(cell (contents ((expr ("\\" @text.math.start.left ("str")+ @text.math.start.right "{")) (expr "}" @text.math.end) (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))))
(cell (contents (expr "\\" @text.math.start.left ("str")+ @text.math.start.right "{" "}" @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))))
(cell (contents (expr "\\" @text.math.start.left ("str")+ @text.math.start.right @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))))

(drawer (contents ((expr "*" @bold.start _) (expr _ "*" @bold.end) (#org-is-valid-markup-range? @bold.start @bold.end))))
(drawer (contents (expr "*" @bold.start _ "*" @bold.end (#org-is-valid-markup-range? @bold.start @bold.end))))
(drawer (contents ((expr "~" @code.start _) (expr _ "~" @code.end) (#org-is-valid-markup-range? @code.start @code.end))))
(drawer (contents (expr "~" @code.start _ "~" @code.end (#org-is-valid-markup-range? @code.start @code.end))))
(drawer (contents ((expr "/" @italic.start _) (expr _ "/" @italic.end) (#org-is-valid-markup-range? @italic.start @italic.end))))
(drawer (contents (expr "/" @italic.start _ "/" @italic.end (#org-is-valid-markup-range? @italic.start @italic.end))))
(drawer (contents ((expr "_" @underline.start _) (expr _ "_" @underline.end) (#org-is-valid-markup-range? @underline.start @underline.end))))
(drawer (contents (expr "_" @underline.start _ "_" @underline.end (#org-is-valid-markup-range? @underline.start @underline.end))))
(drawer (contents ((expr "=" @verbatim.start _) (expr _ "=" @verbatim.end) (#org-is-valid-markup-range? @verbatim.start @verbatim.end))))
(drawer (contents (expr "=" @verbatim.start _ "=" @verbatim.end (#org-is-valid-markup-range? @verbatim.start @verbatim.end))))
(drawer (contents ((expr "+" @strikethrough.start _) (expr _ "+" @strikethrough.end) (#org-is-valid-markup-range? @strikethrough.start @strikethrough.end))))
(drawer (contents (expr "+" @strikethrough.start _ "+" @strikethrough.end (#org-is-valid-markup-range? @strikethrough.start @strikethrough.end))))
(drawer (contents ((expr "[" @hyperlink.start . "[" _) (expr _ "]" . "]" @hyperlink.end) (#org-is-valid-hyperlink-range? @hyperlink.start @hyperlink.end))))
(drawer (contents (expr "[" @hyperlink.start . "[" _  "]" . "]" @hyperlink.end (#org-is-valid-hyperlink-range? @hyperlink.start @hyperlink.end))))
(drawer (contents ((expr ("\\" @text.math.start.left "(" @text.math.start.right)) (expr ("\\" ")" @text.math.end)) (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))))
(drawer (contents (expr "\\" @text.math.start.left "(" @text.math.start.right "\\" ")" @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))))
(drawer (contents ((expr ("\\" @text.math.start.left ("str")+ @text.math.start.right "{")) (expr "}" @text.math.end) (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))))
(drawer (contents (expr "\\" @text.math.start.left ("str")+ @text.math.start.right "{" "}" @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))))
(drawer (contents (expr "\\" @text.math.start.left ("str")+ @text.math.start.right @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))))
