 (expr "*" @bold)
 (expr "/" @italic)
 (expr "~" @code)
 (expr "_" @underline)
 (expr "=" @verbatim)
 (expr "+" @strikethrough)
 (expr "[" @link.start)
 (expr "]" @link.end)
 (expr "[" @date_inactive.start "num" "-" "num" "-" "num")
 (expr "]" @date_inactive.end)
 (expr "<" @date_active.start "num" "-" "num" "-" "num")
 (expr ">" @date_active.end)
 (expr "\\" "str" @latex.plain)
 (expr "\\" "(" @latex.bracket.start)
 (expr "\\" ")" @latex.bracket.end)
 (expr "\\" "{" @latex.curly.start)
 (expr "\\" "}" @latex.curly.end)
 (expr "\\" "[" @latex.square.start)
 (expr "\\" "]" @latex.square.end)
